version: '3.8'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP Service
  php:
    build:
      context: ./.docker/php
      args:
        HOST_UID: $HOST_UID
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      mysql:
        condition: service_healthy

  # MySQL Service
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trial
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

# Volumes
volumes:

  mysqldata: